# Decision Tree


For this problem, you will be implementing a Decision Tree classifier that works on discrete (categorical) features. Although a relatively simple learning algorithm, the Decision Tree is often used as a fundamental building block for more powerful (and popular) models such as Random Forest and Gradient Boosted ensembles. 

You should base your solution on the [ID3](https://en.wikipedia.org/wiki/ID3_algorithmhttps://en.wikipedia.org/wiki/ID3_algorithm) algorithm. This is a basic tree-learning algorithm that greedly grows a tree based on _information gain_ (reduction in entropy). Please refer to Chapter 3 of _Machine Learning_ by Tom M. Mitchell for more details. 


We have provided some skeleton code for the classifier, along with a couple of utility functions in the [decision_tree.py](./decision_tree.py) module. Please fill out the functions marked with `TODO` and feel free to add extra constructor arguments as you see fit (just make sure the default constructor solves the first dataset).


In [106]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


We begin by loading necessary packages. Below follows a short description of the imported modules:

- `numpy` is the defacto python package for numerical calculation. Most other numerical libraries (including pandas) is based on numpy.
- `pandas` is a widely used package for manipulating (mostly) tabular data
- `decision_tree` refers to the module in this folder that should be further implemented by you

Note: The `%autoreload` statement is an [IPython magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html) that automatically reloads the newest version of all imported modules within the cell. This means that you can edit the `decision_tree.py` file and just rerun this cell to get the updated version.

In [107]:

import numpy as np 
import pandas as pd 


## [1] First Dataset

The first dataset is a toy problem lifted from Table 3.2 in the Machine Learning textbook. The objective is to predict whether a given day is suitable for playing tennis based on several weather conditions. 

### [1.1] Load Data

We begin by loading data from the .csv file located in the same folder as this notebook.

In [117]:
data_1 = pd.read_csv('data_1.csv')
data_1

Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

### [1.2] Fit and Evaluate Model

Next we fit and evaluate a Decision Tree over the dataset. We first partition the data into the dependent (`y` = Play Tennis) and independent (`X` = everything else) variables. We then initialize a Decision Tree learner and fit it to all the data. Finally, we evaluate the model over the same data by calculating its accuracy, i.e. the fraction of correctly classified samples.

Note that `.fit` and `.predict` will crash until you implement these two methods in [decision_tree.py](./decision_tree.py).

Assuming that you've correctly implemented the ID3 algorithm as described in the course textbook, you should expect the model to perfectly fit the training data.

**Accepted Performance:** Accuracy = 100%

In [150]:
%autoreload
import decision_tree as dt  # <-- Your implementation
# Separate independent (X) and dependent (y) variables
X = data_1.drop(columns=['Play Tennis'])
y = data_1['Play Tennis']

# Create and fit a Decrision Tree classifier
model_1 = dt.DecisionTree()  # <-- Should work with default constructor
model_1.fit(X, y)

# Verify that it perfectly fits the training set
print(f'Accuracy: {dt.accuracy(y_true=y, y_pred=model_1.predict(X)) * 100 :.1f}%')

Outlook information gain: 0.2467
Temperature information gain: 0.0292
Humidity information gain: 0.1518
Wind information gain: 0.0481
[0.24674982 0.02922257 0.1518355  0.04812703]
Temperature information gain: 0.5710
Humidity information gain: 0.9710
Wind information gain: 0.0200
[0.57095059 0.97095059 0.01997309]
Temperature information gain: 0.0000
Wind information gain: 0.0000
[0. 0.]
Temperature information gain: 0.0000
Wind information gain: 0.0000
[0. 0.]
Temperature information gain: 0.0200
Humidity information gain: 0.0200
Wind information gain: 0.9710
[0.01997309 0.01997309 0.97095059]
Temperature information gain: 0.0000
Humidity information gain: 0.0000
[0. 0.]
Temperature information gain: 0.0000
Humidity information gain: 0.0000
[0. 0.]
Temperature information gain: 0.0000
Humidity information gain: 0.0000
Wind information gain: 0.0000
[0. 0. 0.]
Accuracy: 100.0%


### [1.3] Inspect Classification Rules

A big advantage of Decision Trees is that they are relatively transparent learners. By this we mean that it is easy for an outside observer to analyse and understand how the model makes its decisions. The problem of being able to reason about how a machine learning model reasons is known as _Explainable AI_ and is often a desirable property of machine learning systems.

Every time a Decision Tree is evaluated, the datapoint is compared against a set of nodes starting at the root of the tree and (typically) ending at one of the leaf nodes. An equivalent way to view this reasoning is as an implication rule ($A \rightarrow B$) where the antecedent ($A$) is a conjunction of of attribute values and the consequent ($B$) is the predicted label. For instance, if a path down the tree first checks if Outlook=Rain, then checks if Wind=Strong, and then predicts Play Tennis=No, this line of reasoning can be represented as:

- If $Outlook=Rain \cap Wind=Strong \rightarrow$ then predict $Play Tennis = No$

We will leverage this property to export the decision tree you just created as a set of rules. For the subsequent cell to work, you must also have implemented the `.get_rules()` method in the provided boilerplate code.

In [151]:
%autoreload
import decision_tree as dt  # <-- Your implementation

for rules, label in model_1.get_rules():
    conjunction = ' ∩ '.join(f'{attr}={value}' for attr, value in rules)
    print(f'{"✅" if label == "Yes" else "❌"} {conjunction} => {label}')

✅ Outlook=Overcast => Yes
❌ Outlook=Sunny ∩ Humidity=High => No
✅ Outlook=Sunny ∩ Humidity=Normal => Yes
✅ Outlook=Rain ∩ Wind=Weak => Yes
❌ Outlook=Rain ∩ Wind=Strong => No


## [2] Second Dataset

The second dataset involves predicting whether an investment opportunity will result in a successful `Outcome` or not. To make this prediction, you are given a dataset of 200 historical$^1$ business ventures and their outcome, along with the following observed features:

- Whether the business oportunity is in a lucurative market or not 
- Whether the presented business idea has a competitive advantage
- Whether the second opinion from another investor is positive or not 
- The founder's previous experience with startups
- The founder's favorite color
- The founder's [Zodiac Sign](https://en.wikipedia.org/wiki/Astrology)

---
[1] Disclaimer: The dataset is not based on real-world business ventures. It is synthetic and generated by us. Also, it should not be considered financial advice.

### [2.1] Load Data

This dataset can also be found in a .csv file in the same folder as this notebook.

In [170]:
data_2 = pd.read_csv('data_2.csv')
#data_2 = data_2.drop(columns='Founder Zodiac')

data_2

Founder Zodiac Founder Experience Second Opinion Competitive Advantage  \
0           cancer           moderate       negative                   yes   
1           cancer               high       positive                   yes   
2          scorpio                low       negative                    no   
3           cancer                low       negative                    no   
4         aquarius                low       positive                   yes   
..             ...                ...            ...                   ...   
195      capricorn           moderate       positive                    no   
196       aquarius                low       negative                    no   
197         cancer           moderate       negative                    no   
198          virgo           moderate       negative                    no   
199      capricorn           moderate       negative                   yes   

    Founder Favourite Color Lucurative Market  Outcome  Split  
0                     green               yes  success  train  
1                      blue                no  failure  train  
2                     green                no  failure  train  
3                     black               yes  failure  train  
4                       red               yes  success  train  
..                      ...               ...      ...    ...  
195                     red               yes  failure   test  
196                  yellow                no  failure   test  
197                  yellow               yes  success   test  
198                   black               yes  failure   test  
199                   white               yes  failure   test  

[200 rows x 8 columns]

### [2.2] Split Data

We've also taken the liberty to pre-split the dataset into three different sets:

- `train` contains 50 samples that you should use to generate the tree
- `valid` contains 50 samples that you can use to evaluate different preprocessing methods and variations to the tree-learning algorithm.
- `test` contains 100 samples and should only be used to evaluate the final model once you're done experimenting.

In [171]:
%autoreload
import decision_tree as dt  # <-- Your implementation

data_2_train = data_2.query('Split == "train"')
data_2_valid = data_2.query('Split == "valid"')
data_2_test = data_2.query('Split == "test"')
X_train, y_train = data_2_train.drop(columns=['Outcome', 'Split']), data_2_train.Outcome
X_valid, y_valid = data_2_valid.drop(columns=['Outcome', 'Split']), data_2_valid.Outcome
X_test, y_test = data_2_test.drop(columns=['Outcome', 'Split']), data_2_test.Outcome
data_2.Split.value_counts()

test     100
train     50
valid     50
Name: Split, dtype: int64

### [2.3] Fit and Evaluate Model

You may notice that the basic ID3 algorithm you developed for the first dataset does not generalize well when applied straight to this problem. Feel free to add extra functionality to it and/or the data preprocessing pipeline that might improve performance on the validation (and ultimately test set).

**Accepted Performance:** Test set accuracy >= 75%

In [173]:
%autoreload
import decision_tree as dt  # <-- Your implementation

# Fit model (TO TRAIN SET ONLY)
model_2 = dt.DecisionTree()  # <-- Feel free to add hyperparameters 
model_2.fit(X_train, y_train, truth_value='success')
r = model_2.get_rules()
print(len(r))
for rules, label in r:
    conjunction = ' ∩ '.join(f'{attr}={value}' for attr, value in rules)
    print(f'{"✅" if label == "success" else "❌"} {conjunction} => {label}')
#print(f'Train: {dt.accuracy(y_train, model_2.predict(X_train)) * 100 :.1f}%')
#print(f'Valid: {dt.accuracy(y_valid, model_2.predict(X_valid)) * 100 :.1f}%')

Founder Zodiac information gain: 0.1585
Founder Experience information gain: 0.0014
Second Opinion information gain: 0.0001
Competitive Advantage information gain: 0.0297
Founder Favourite Color information gain: 0.0913
Lucurative Market information gain: 0.0143
[1.58511589e-01 1.44920511e-03 6.13428545e-05 2.96610100e-02
 9.12917815e-02 1.43227627e-02]
Founder Experience information gain: 0.7219
Second Opinion information gain: 0.7219
Competitive Advantage information gain: 0.7219
Founder Favourite Color information gain: 0.7219
Lucurative Market information gain: 0.7219
[0.72192809 0.72192809 0.72192809 0.72192809 0.72192809]
Second Opinion information gain: 0.0000
Competitive Advantage information gain: 0.0000
Founder Favourite Color information gain: 0.0000
Lucurative Market information gain: 0.0000
[0. 0. 0. 0.]
Second Opinion information gain: 0.0000
Competitive Advantage information gain: 0.0000
Founder Favourite Color information gain: 0.0000
Lucurative Market information gain:

Founder Favourite Color information gain: 0.0000
Lucurative Market information gain: 0.0000
[0. 0. 0. 0. 0.]
Founder Experience information gain: 0.0000
Second Opinion information gain: 0.0000
Competitive Advantage information gain: 0.0000
Founder Favourite Color information gain: 0.0000
Lucurative Market information gain: 0.0000
[0. 0. 0. 0. 0.]
gemini
capricorn
leo
low
high
moderate
low
high
moderate
low
high
low
moderate
high
low
moderate
high
low
moderate
negative
positive
positive
positive
no
yes
yes
no
yes
no
yes
yellow
green
green
red
green
yellow
36
✅ Founder Zodiac=gemini => success
❌ Founder Zodiac=capricorn => failure
❌ Founder Zodiac=leo => failure
❌ Founder Zodiac=cancer ∩ Founder Experience=low => failure
❌ Founder Zodiac=cancer ∩ Founder Experience=high => failure
❌ Founder Zodiac=pisces ∩ Founder Experience=moderate => failure
❌ Founder Zodiac=pisces ∩ Founder Experience=low => failure
❌ Founder Zodiac=taurus ∩ Founder Experience=high => failure
❌ Founder Zodiac=scorpio

## [3] Further steps (optional)

If you're done with the assignment but want to some more challenges; consider the following:

- Make a Decision Tree learner that can handle numerical attributes
- Make a Decision Tree learner that can handle numerical targets (regresion tree)
- Try implementing [Random Forest](https://en.wikipedia.org/wiki/Random_forest) on top of your Decision Tree algorithm

If you need more data for experimenting, UC Irvine hosts a [large repository](https://archive.ics.uci.edu/ml/datasets.php) of machine learning datasets.
